### ISSUE TITLE
Subscribe button in Newsletter - to change to I JOIN

### ISSUE THREAD

**Issue by ksyu-sniper** [dawidsky/zenwithxenia#18]
@dawidsky

1) IMPORTANT - to change the text

  - Instead of **JOIN OUR NEWSLETTERS**  - JOIN MY INNER CIRCLE!

 **And then small text to replace with -** 

Want to get newsletter with MAGICAL touch? To GET healthy & happy Tips, Inspiration and exclusive Freebies? 
I aim to send out only AWERSOME emails to help you live your HAPPY life journey 🙂.

- and if it's possible to change button SUBSCRIBE - then to write **I JOIN!**

2)  for now it is just the question. if not then not, I will figure it out somehow... not so important now.
now it is only 1 field for emails
can we add + 1 for names also? (I don't know where it goes in the site further) - logically it should be like DataBase then behind.

**Comment by ksyu-sniper** [comment]
@dawidsky

for now it is just the question.
now it is only 1 field for emails
can we add + 1 for names also? (I dont know where it goes in the site further) - logically it should be like Data Base then behind.
if not then not, will figure it out somehow...

**Comment by dawidsky** [comment]
Done.
Work on Subscribe button to say I Join!

**Comment by ksyu-sniper** [comment]
baby, its super nice now.
I just had a look with more fresh eyes n the text and wanted different accents on the text.
So can you copy -paste this instead of whats is now.

Want to get newsletter with MAGICAL touch? To get HEALTHY & HAPPY Tips, Inspiration and EXCLUSIVE Freebies? I aim to send out only AWESOME emails to help you live your HAPPY Life Journey.

**Comment by dawidsky** [comment]
> Want to get newsletter with MAGICAL touch? To get HEALTHY & HAPPY Tips, Inspiration and EXCLUSIVE Freebies? I aim to send out only AWESOME emails to help you live your HAPPY Life Journey.

Done.

**Comment by dawidsky** [comment]
Subscribe button changed to I JOIN!
(this is not really sounding correct grammatically?)

file:
C:\Users\kowal\Dev\Hugo\Sites\zenwithxenia\themes\liva-hugo\layouts\partials\footer.html
line: 13
