### ISSUE TITLE
IMPORTANT! TO DELETE FIRST PICTURE IN THE POSTS. they duplicate pictures from the main page. no need. (to change template)

### ISSUE THREAD

**Issue by ksyu-sniper** [dawidsky/zenwithxenia#7]
@dawidsky 

Is it possible to delete in the post itself top picture? when opening the final page of post - on the top there is a link to the picture of the post (which we see on the main page and blog common page).

SO, if I need to insert any picture I can do it! or video.. But mostly (and it is really important) - I dont need to duplicate the same picture from the main page (where you can observe all posts) ! Extremely important thing. I checked now - it is duplicated, so like build in the system of site, I cannot delete it myself.
I

**Comment by dawidsky** [comment]
Done.
file:
\themes\liva-hugo\layouts\_default\single.html
line: 20-22
